"""
DrHall-inspired baseline implementation.

Adapts the six base metamorphic relations from DrHall (Wu et al., FSE 2025,
"Detecting and Reducing the Factual Hallucinations of Large Language Models
with Metamorphic Testing") to HONEST's KG-rule-based QA dataset.

The key idea: *hallucinated answers are unstable* — if the LLM is asked the
*same* question through a different "execution path" (via a metamorphic
transformation), the follow-up answer should be consistent with the original.
Inconsistency flags a potential hallucination.

Metamorphic Relations (MRs)
---------------------------
QMR1 (Chain of Thought)        – append "Please think step by step …"
QMR2 (Multilingual Voting)     – translate the question into 3 languages
QMR3 (Problem Optimization)    – paraphrase / reword the question
QMR4 (Adding External Knowledge) – prepend known facts as evidence.
                                  ⚠ EXCLUDED from our experiments: the paper
                                  retrieves external evidence from Wikipedia,
                                  which our dataset lacks; reusing the KG rule
                                  that generated the question leaks the answer.
                                  Kept here as library code only.
AMR1 (General Question)        – ask "[original answer]. Is this statement NOT true?"
AMR2 (Multi-Choice Question)   – construct a multiple-choice question with distractors

Paper-faithfulness notes (see baselines/drhall/ALIGNMENT_PLAN.md)
-----------------------------------------------------------------
* QMR2 follows the paper: the *question* is translated into Spanish/German/
  Dutch, producing **three independent** follow-up questions that are answered
  separately and then **voted** (see ``qmr2_vote``). The original paper uses
  Google Translate; here translation is injected via ``translate_fn`` /
  ``translate_llm_fn`` (API preferred, LLM fallback). Without a translator the
  questions cannot be translated and a warning is emitted (degraded mode).
* AMR1 puts the *original answer* (optionally declarativized) inside the
  negation template, matching the paper — not a mechanical
  "<question> – the answer is <answer>" concatenation.
* QMR3 uses the LLM paraphrase by default; the rule-based regex fallback is
  *off* unless explicitly enabled (``allow_rule_based_fallback=True``).

Evaluation
----------
Consistency between original and follow-up answers is assessed with the
paper's exact answer-simplification and consistency-judge prompts
(``ANSWER_SIMPLIFY_PROMPT``, ``CONSISTENCY_JUDGE_PROMPT``) plus
``build_consistency_judge_prompt`` / ``parse_consistency`` helpers.
"""

import inspect
import json
import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set

import pandas as pd

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums & data-classes
# ---------------------------------------------------------------------------

class DrHallMR(str, Enum):
    """The six base metamorphic relations from DrHall."""

    QMR1 = "QMR1_ChainOfThought"
    QMR2 = "QMR2_MultilingualVoting"
    QMR3 = "QMR3_ProblemOptimization"
    QMR4 = "QMR4_ExternalKnowledge"
    AMR1 = "AMR1_GeneralQuestion"
    AMR2 = "AMR2_MultiChoice"
    # Composite MR (paper §3.4, Table 2). NOT a base MR — it is built by stacking
    # the four QMRs. Kept in the enum so it has a stable mr_type string + a
    # dedicated dataset column, but excluded from ALL_MRS (the six base MRs).
    CMR3 = "CMR3_Composite"


@dataclass
class DrHallMutation:
    """A single follow-up question generated by one of the DrHall MRs."""

    mr_type: str                  # e.g. "QMR1_ChainOfThought"
    follow_up_question: str       # the transformed question to ask the LLM
    original_question: str        # the original question (for reference)
    expected_relation: str        # human-readable description of expected relation
    metadata: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Prompt templates (verbatim from the DrHall paper, FSE 2025)
# ---------------------------------------------------------------------------
# Each constant below is annotated with its provenance:
#   [PAPER-VERBATIM]  – reproduced exactly from the paper
#   [AUTHORED]        – not released in the paper, written for this codebase
#   [ADAPTED]         – paper template adapted to the KG-rule dataset

# QMR1 (Chain of Thought) – paper Section 3.2, QMR1.  [PAPER-VERBATIM]
COT_SUFFIX = (
    " Please think step by step to solve this problem and give the answer."
)

# QMR2 (Multilingual Voting) – paper Section 3.2, QMR2.
# The paper translates the *question* via Google Translate into Spanish,
# German and Dutch and answers each independently.  We do NOT bundle the three
# languages into one prompt (that would collapse three execution paths into one
# and make voting impossible).  Instead, one mutation is produced per language.
# [ADAPTED] The translator is injected (translate_fn / translate_llm_fn) rather
# than calling Google Translate directly.
QMR2_LANGUAGES = ["es", "de", "nl"]

# Map language code -> display name (used in metadata / debugging).
LANGUAGE_NAMES = {"es": "Spanish", "de": "German", "nl": "Dutch"}

# Number of retries for LLM translation when a reasoning model occasionally
# returns an empty text block (with HTTP 200).
LLM_TRANSLATE_RETRIES = 3

# Prompt used to ask the LLM to *translate* the question into a target language.
# [AUTHORED] – the paper uses Google Translate, which exposes no prompt.
#
# Heavily emphasizes "translate only, do not answer". Shorter earlier prompts were
# misread by some models (e.g. deepseek-v4-flash) as an answering task, so they
# returned "Sí." / "Ja." / "C" style answers instead of translations (see the
# QMR2 quality checks in IMPLEMENTATION_VS_PAPER). This prompt prevents that
# behavior from several angles: explicit role (translator), explicit ban on
# answering/explaining, requirement to preserve the question mark, and a clear
# input/output boundary.
TRANSLATE_PROMPT = (
    "You are a professional translator. Your ONLY task is to translate the "
    "English question below into {language}.\n"
    "Rules:\n"
    "- Output ONLY the translated question, nothing else.\n"
    "- Do NOT answer, solve, or respond to the question under any circumstances.\n"
    "- Do NOT add explanations, notes, introductions, or prefixes such as "
    "\"Translation:\".\n"
    "- Do NOT wrap the output in quotation marks.\n"
    "- Preserve the meaning, all named entities, numbers, and the trailing "
    "question mark.\n\n"
    "English question:\n{question}\n\n"
    "{language} translation:"
)

# Minimum length for a cleaned translation; outputs shorter than this (and not
# already caught by the answer-token regex) are degenerate. A real translation
# of any source question is far longer than this; 8 is a permissive floor that
# only rejects stray single-token garbage.
TRANSLATION_MIN_LENGTH = 8

# Bare answer tokens the model emits when it answers instead of translating.
# Matched against the WHOLE cleaned output (case-insensitive). A real
# translation (a full sentence) never equals one of these.
_ANSWER_TOKEN_RE = re.compile(
    r"^\s*(?:"
    r"yes|no|true|false|correct|incorrect|right|wrong|unknown|none"
    r"|sí|si|cierto|falso|verdadero"
    r"|ja|nein|nee|neen|richtig|falsch|wahr"
    r"|juist|onjuist|waar|onwaar"
    r"|[a-d1-9]"
    r")\s*[.。!！?？]?\s*$",
    re.IGNORECASE,
)

# Multiple-choice answer prefix: "A. ...", "B) ...", "c: ...". When the
# model treats a translation request as answering an MC question, it
# prepends the chosen option letter. Our source questions never start this
# way, so a leading option prefix unambiguously marks an answer, not a
# translation.
_OPTION_PREFIX_ANSWER_RE = re.compile(r"^\s*[A-Da-d]\s*[.):]\s+\S")

# A Latin letter (incl. accented Latin). An es/de/nl translation must
# contain at least one; if it has none, the model drifted to a non-Latin
# script (e.g. emitted a whole Chinese sentence for German). A faithful
# translation may *contain* a few non-Latin entity chars (e.g. the hanzi
# 丘 preserved verbatim); only a translation with NO Latin letters at all
# is rejected, so legitimate entity-name preservation is kept.
_LATIN_LETTER_RE = re.compile(r"[A-Za-z\xc0-\xd6\xd8-\xf6\xf8-\xff]")

# Prefixes / wrappers the model sometimes adds despite instructions.
_TRANSLATION_PREFIX_RE = re.compile(
    r"^\s*(?:translation|traducción|traduccion|übersetzung|vertaling"
    r"|spanish|german|dutch|español|espanol|deutsch|nederlands"
    r"|answer|respuesta|antwort|antwoord)\s*[:：]\s*",
    re.IGNORECASE,
)

# QMR3 (Problem Optimization / paraphrase) – paper Section 3.2, QMR3.  [PAPER-VERBATIM]
PARAPHRASE_PROMPT = (
    "I hope you can serve as a copywriter and text polishing officer. "
    "I will send you the English text, and you can help me improve the version. "
    "I hope you can change the words and structure of the sentence as much as possible. "
    "Keep the same meaning, but make them easier to understand. "
    "You only need to polish the content without explaining the questions and requirements "
    "raised in the content.\n\n"
    "Original text:\n{question}"
)

# QMR4 (Adding External Knowledge) – paper Section 3.2, QMR4.  [PAPER-VERBATIM]
# "Known: [Evidence] May I ask: [Original Question]."
EXTERNAL_KNOWLEDGE_TEMPLATE = (
    "Known: [{evidence}]\n"
    "May I ask: [{question}]"
)

# AMR1 (General Question) – paper Section 3.3, AMR1.  [PAPER-VERBATIM]
# "[Original Answer] Is this statement not true?"
AMR1_NEGATION_TEMPLATE = (
    "[{statement}] Is this statement not true?"
)

# Prompt to declarativize an answer into a natural statement for AMR1.
# [AUTHORED] – the paper uses the LLM's own declarative answer directly; this
# prompt converts a short dataset answer into such a statement.
AMR1_STATEMENT_PROMPT = (
    "Rewrite the following answer to the given question as a single, natural, "
    "self-contained declarative statement. Output only the statement.\n\n"
    "Question: {question}\n"
    "Answer: {answer}"
)

# AMR2 Step 1: Simplify the answer (paper Section 3.3, AMR2).  [PAPER-VERBATIM]
AMR2_SIMPLIFY_PROMPT = (
    "Try to summarize the answer into one word or one phrase.\n\n"
    "Answer: {answer}"
)

# AMR2 Step 2: Generate distractors (paper Section 3.3, AMR2).  [PAPER-VERBATIM]
AMR2_DISTRACTOR_PROMPT = (
    "Please provide two phrases similar to [{simplified_answer}]. "
    "Note: The phrases provided should be of a similar type to the original phrase, "
    "but the meaning cannot be identical. "
    "I want you to only reply with similar phrases, without writing any explanations."
)

# AMR2 Step 3: Multi-choice question format (paper Table 1, AMR2 Example).  [PAPER-VERBATIM]
AMR2_CHOICE_TEMPLATE = (
    "{question} "
    "Is it '{option_1}'? Or '{option_2}'? Or '{option_3}'? "
    "Or maybe none of the above answers are correct?"
)

# --- Answer-consistency assessment (paper Section 3.5) ---------------------

# Simplify a long model answer for consistency judgement.  [PAPER-VERBATIM]
ANSWER_SIMPLIFY_PROMPT = "Please try to answer in one sentence.\n\nAnswer: {answer}"

# Judge consistency between the processed original and follow-up answers.
# [PAPER-VERBATIM] (paper Section 3.5)
CONSISTENCY_JUDGE_PROMPT = (
    "Are the above two answers to the question consistent? "
    "Please answer in as few words or phrases as possible. "
    "Do not evaluate the rightness or wrongness of the answer itself. "
    "Note: Yes and right have the same meaning; No and Wrong have the same meaning."
)


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class DrHall:
    """
    DrHall baseline – generates follow-up questions via six MRs for a given
    row from the golden dataset.
    """

    # MRs that operate on the *question* (QMR)
    QUESTION_MRS = [DrHallMR.QMR1, DrHallMR.QMR2, DrHallMR.QMR3, DrHallMR.QMR4]
    # MRs that operate on the *answer* (AMR)
    ANSWER_MRS = [DrHallMR.AMR1, DrHallMR.AMR2]
    ALL_MRS = QUESTION_MRS + ANSWER_MRS
    # Composite MRs (paper §3.4): formed by stacking QMRs. They are NOT base MRs,
    # so they are excluded from ALL_MRS / generate_all_mutations_async (which
    # covers the six base MRs only). CMR3 has its own async generator below.
    COMPOSITE_MRS = [DrHallMR.CMR3]

    def __init__(
        self,
        multilingual_languages: Optional[List[str]] = None,
        paraphrase_llm_fn: Optional[Callable] = None,
        distractor_llm_fn: Optional[Callable] = None,
        simplify_llm_fn: Optional[Callable] = None,
        translate_fn: Optional[Callable[[str, str], str]] = None,
        translate_llm_fn: Optional[Callable] = None,
        statement_llm_fn: Optional[Callable] = None,
        allow_rule_based_fallback: bool = False,
    ):
        """
        Args:
            multilingual_languages: language codes for QMR2. Defaults to ['es','de','nl'].
            paraphrase_llm_fn: async callable(prompt) -> paraphrased_question for QMR3.
            distractor_llm_fn: async callable(question, simplified_answer) -> list[str] for AMR2.
            simplify_llm_fn: async callable(prompt) -> simplified_answer for AMR2 Step 1.
            translate_fn: sync callable(question, lang_code) -> translated_question for QMR2
                          (e.g. a Google-Translate wrapper). Preferred over LLM translation.
            translate_llm_fn: async callable(question, lang_code) -> translated_question,
                              used when no external translator is available.
            statement_llm_fn: async callable(question, answer) -> declarative statement for AMR1.
            allow_rule_based_fallback: if True, QMR3 may fall back to a rule-based
                                       paraphrase when the LLM is unavailable/fails.
                                       Off by default (unfaithful to the paper).
        """
        self.languages = multilingual_languages or list(QMR2_LANGUAGES)
        self.paraphrase_llm_fn = paraphrase_llm_fn
        self.distractor_llm_fn = distractor_llm_fn
        self.simplify_llm_fn = simplify_llm_fn
        self.translate_fn = translate_fn
        self.translate_llm_fn = translate_llm_fn
        self.statement_llm_fn = statement_llm_fn
        self.allow_rule_based_fallback = allow_rule_based_fallback
        # De-duplicate degraded-mode warnings: each category is emitted only once
        # (see _warn_once). On large datasets, repeating the identical warning for
        # every row/language would drown the log; per-row degradation info is
        # already written into each mutation's metadata
        # (degraded / translation_method).
        self._warned: Set[str] = set()

    # ----- QMR1: Chain of Thought -----
    def generate_qmr1(self, question: str, row: Optional[pd.Series] = None) -> DrHallMutation:
        """Append the paper's CoT suffix to the question."""
        follow_up = question.rstrip() + COT_SUFFIX
        return DrHallMutation(
            mr_type=DrHallMR.QMR1.value,
            follow_up_question=follow_up,
            original_question=question,
            expected_relation="Answers should be semantically identical.",
            metadata={"kg_rule": _safe_get(row, "kg_rule"),
                      "honest_mutation_type": _safe_get(row, "mutation_type")},
        )

    # ----- QMR2: Multilingual Voting -----
    def generate_qmr2(
        self, question: str, row: Optional[pd.Series] = None
    ) -> List[DrHallMutation]:
        """
        Generate **one independent follow-up question per language** (paper:
        translate the question into es/de/nl, answer each separately, then vote).

        Synchronous variant: uses ``translate_fn`` if it is a *sync* callable.
        Without a sync translator, the question cannot be translated here — a
        warning is emitted and the mutations are produced in *degraded* mode
        (``translation_method="none"``). Use ``generate_qmr2_async`` for the
        faithful LLM-based translation path.

        Returns a list of mutations (one per language), NOT a single mutation.
        """
        mutations: List[DrHallMutation] = []
        for lang in self.languages:
            translated, method = self._translate_sync(question, lang)
            mutations.append(self._build_qmr2_mutation(
                question, lang, translated, method, row,
            ))
        return mutations

    async def generate_qmr2_async(
        self, question: str, row: Optional[pd.Series] = None
    ) -> List[DrHallMutation]:
        """
        Faithful QMR2 path: translate the question into each language via an
        injected translator (external ``translate_fn`` first, then
        ``translate_llm_fn``). Falls back to degraded mode only if neither is
        available, emitting a warning.
        """
        mutations: List[DrHallMutation] = []
        for lang in self.languages:
            translated, method = await self._translate_async(question, lang)
            mutations.append(self._build_qmr2_mutation(
                question, lang, translated, method, row,
            ))
        return mutations

    def _translate_sync(self, question: str, lang: str) -> "tuple[str, str]":
        """Try a sync translator; return (translated_text, method)."""
        if self.translate_fn is not None and not _is_async_callable(self.translate_fn):
            try:
                translated = self.translate_fn(question, lang)
                cleaned = self._clean_translation(translated)
                if self._translation_valid(cleaned, question, lang):
                    return cleaned, "translate_fn"
            except Exception as exc:  # noqa: BLE001 – log and degrade
                logger.warning("QMR2 translate_fn failed (%s): %s", lang, exc)
        # Degraded mode: no sync translator wired. The whole batch shares the
        # same root cause, so we warn only once; per-row degradation status is
        # written into mutation metadata (degraded / translation_method).
        self._warn_once(
            "qmr2_no_sync_translator",
            "QMR2: no sync translator available; producing degraded "
            "(untranslated) mutations for all configured languages. Pass "
            "translate_fn or use generate_qmr2_async for faithful translation. "
            "(Emitted only once; per-row degradation is recorded in metadata.)",
        )
        return question, "none"

    async def _translate_async(
        self, question: str, lang: str, mr_label: str = "QMR2"
    ) -> "tuple[str, str]":
        """Translate via translate_fn (sync or async) or translate_llm_fn.

        ``mr_label`` only adjusts the degraded-mode warning text so it names the
        calling MR (e.g. "CMR3") rather than always "QMR2".
        """
        # 1. External sync translator.
        if self.translate_fn is not None and not _is_async_callable(self.translate_fn):
            try:
                translated = self.translate_fn(question, lang)
                cleaned = self._clean_translation(translated)
                if self._translation_valid(cleaned, question, lang):
                    return cleaned, "translate_fn"
            except Exception as exc:  # noqa: BLE001
                logger.warning("QMR2 translate_fn failed (%s): %s", lang, exc)
        # 2. External async translator.
        if self.translate_fn is not None and _is_async_callable(self.translate_fn):
            try:
                translated = await self.translate_fn(question, lang)
                cleaned = self._clean_translation(translated)
                if self._translation_valid(cleaned, question, lang):
                    return cleaned, "translate_fn"
            except Exception as exc:  # noqa: BLE001
                logger.warning("QMR2 async translate_fn failed (%s): %s", lang, exc)
        # 3. LLM-based translation fallback.
        if self.translate_llm_fn is not None:
            prompt = TRANSLATE_PROMPT.format(
                language=LANGUAGE_NAMES.get(lang, lang), question=question,
            )
            # Reasoning models (e.g. deepseek-v4-flash) have two failure modes:
            # (1) a response returns only a thinking block with an empty text block
            # (HTTP still 200); (2) the translation task is misread as an answering
            # task, returning "Sí." / "C" style answers. The client's retry only
            # covers thrown exceptions, so here we retry a few times for results
            # that are "empty / ERROR / look like an answer / abnormal length /
            # leaked non-Latin chars", using the improved prompt +
            # _translation_valid to filter them out.
            for attempt in range(LLM_TRANSLATE_RETRIES):
                try:
                    raw = await self.translate_llm_fn(prompt, lang)
                except Exception as exc:  # noqa: BLE001
                    self._warn_once(
                        f"{mr_label.lower()}_translate_exception",
                        "%s: translate_llm_fn raised (%s); %s. Will not retry "
                        "on exception.",
                        mr_label, lang, exc,
                    )
                    break
                cleaned = self._clean_translation(raw)
                if self._translation_valid(cleaned, question, lang):
                    return cleaned, "translate_llm_fn"
            else:
                # Retries exhausted and still failed validation -> fall through to
                # the degraded path below (warned only once).
                pass
        # 4. Degraded mode. The whole batch shares the same root cause, so we warn
        # only once per MR category; per-row degradation status is written into
        # mutation metadata.
        self._warn_once(
            f"{mr_label.lower()}_no_translator",
            "%s: no translator available; producing degraded (untranslated) "
            "mutations for all configured languages. Pass translate_fn or "
            "translate_llm_fn for faithful translation. (Emitted only once per "
            "MR; per-row degradation is recorded in metadata.)",
            mr_label,
        )
        return question, "none"

    def _build_qmr2_mutation(
        self,
        question: str,
        lang: str,
        translated_question: str,
        translation_method: str,
        row: Optional[pd.Series],
    ) -> DrHallMutation:
        degraded = translation_method == "none"
        return DrHallMutation(
            mr_type=DrHallMR.QMR2.value,
            follow_up_question=translated_question,
            original_question=question,
            expected_relation=(
                "All language variants should yield the same answer."
                + (" [DEGRADED: question not translated]" if degraded else "")
            ),
            metadata={
                "language": lang,
                "language_name": LANGUAGE_NAMES.get(lang, lang),
                "translation_method": translation_method,
                "degraded": degraded,
                "kg_rule": _safe_get(row, "kg_rule"),
                "honest_mutation_type": _safe_get(row, "mutation_type"),
            },
        )

    @staticmethod
    def qmr2_vote(answers: List[str]) -> Dict[str, Any]:
        """
        Paper Section 3.2, QMR2: the three per-language answers (after being
        back-translated into English by the caller) are voted; the answer with
        the highest count is the follow-up answer of QMR2.

        Args:
            answers: list of (back-translated) answers, one per language.

        Returns:
            dict with ``voted_answer``, ``vote_counts`` and ``tie``.
        """
        answers = [str(a).strip() for a in (answers or []) if a is not None and str(a).strip()]
        if not answers:
            return {"voted_answer": None, "vote_counts": {}, "tie": False}
        counts = Counter(answers)
        top_count = max(counts.values())
        winners = [a for a, c in counts.items() if c == top_count]
        return {
            "voted_answer": winners[0],
            "vote_counts": dict(counts),
            "tie": len(winners) > 1,
        }

    def _warn_once(self, key: str, message: str, *args: Any) -> None:
        """Emit ``message`` at WARNING level at most once per ``key``.

        Degraded mode (e.g. when no translator is wired) is *intentional* during
        the offline mutation-generation phase, and per-row degradation info is
        already recorded in each mutation's ``metadata``
        (``degraded`` / ``translation_method``). Emitting one warning per row and
        per language would drown the large dataset's log in identical sentences,
        so here we collapse them into a single warning per category. Per-row
        observability is still provided via metadata.
        """
        if key in self._warned:
            return
        self._warned.add(key)
        logger.warning(message, *args)

    @staticmethod
    def _translation_ok(text: Any) -> bool:
        """True if ``text`` is non-empty and not an ``"ERROR: ..."`` sentinel.

        The project's LLM client returns an ``"ERROR: ..."`` string on failure
        rather than raising an exception, so such strings must be explicitly
        rejected — otherwise a failed translation would be silently stored as a
        real (but incorrect) translation.

        Note: this is the *low-level* availability check. Use
        :meth:`_translation_valid` for the full faithfulness check (it builds
        on this one and also rejects answers-in-place-of-translations).
        """
        if not text:
            return False
        s = str(text).strip()
        if not s:
            return False
        return not s.upper().startswith("ERROR:")

    @staticmethod
    def _clean_translation(text: Any) -> str:
        """Normalize a raw translator output before validation.

        Strips the occasional ``Translation:`` / ``Spanish:`` prefix the model
        adds, surrounding paired quotes, and leading/trailing whitespace. A
        faithful translation should not carry any of these, and removing them
        makes the subsequent validation more stable.
        """
        if not text:
            return ""
        s = str(text).strip()
        # Strip a single pair of surrounding quotes (« », „ ", " ', etc.).
        if len(s) >= 2 and s[0] in "“”«„\"'" and s[-1] in "“”»\"'":
            s = s[1:-1].strip()
        # Strip a leading "Translation:" / "Spanish:" style prefix.
        s = _TRANSLATION_PREFIX_RE.sub("", s).strip()
        return s

    @classmethod
    def _translation_valid(
        cls, cleaned: Any, original_question: str, lang: str
    ) -> bool:
        """Full faithfulness check for a candidate translation.

        Rejects, beyond empty/ERROR outputs (:meth:`_translation_ok`):

        1. **Bare answer token**: the model returned a token such as ``"Sí."``,
           ``"Ja."`` or ``"C"`` instead of translating (the most common failure
           for yes/no questions).
        2. **Multiple-choice answer prefix**: an output like ``"A. Shen Woo
           ... is from ..."`` — the model picked an MC option and answered
           rather than translating. Our source questions never start this way.
        3. **Non-Latin drift**: the output has *no Latin letters at all* (the
           model emitted a whole Chinese/Cyrillic/... sentence for es/de/nl).
           Note a faithful translation may still contain non-Latin entity chars
           (e.g. the hanzi 丘); only zero-Latin outputs are rejected.
        4. **Lost interrogative**: if the source is a question (ends in ``?``),
           a faithful translation must also end in ``?`` — answer-style outputs
           are declarative statements with no question mark.
        5. **Degenerate length**: shorter than :data:`TRANSLATION_MIN_LENGTH`
           (catches stray garbage not already matched above).

        These rules are precision-tuned on the KG-rule dataset: they target the
        observed failure modes (answering instead of translating) without
        rejecting genuine translations, which may be much shorter than the
        source (the source is inflated by long KG entity descriptions).
        """
        if not cls._translation_ok(cleaned):
            return False
        s = str(cleaned).strip()

        # (1) Bare answer token.
        if _ANSWER_TOKEN_RE.match(s):
            return False

        # (2) Multiple-choice answer prefix ("A. ...", "B) ...").
        if _OPTION_PREFIX_ANSWER_RE.match(s):
            return False

        # (3) No Latin letters at all -> drifted to a non-Latin script.
        if not _LATIN_LETTER_RE.search(s):
            return False

        # (4) Lost the question mark: a question translated must stay a question.
        src = str(original_question or "").rstrip()
        if src.endswith("?") and not s.endswith("?"):
            return False

        # (5) Degenerate single-token garbage.
        if len(s) < TRANSLATION_MIN_LENGTH:
            return False

        return True

    # ----- QMR3: Problem Optimization (paraphrase) -----
    async def generate_qmr3_async(
        self, question: str, row: Optional[pd.Series] = None
    ) -> Optional[DrHallMutation]:
        """
        Paraphrase the question with the paper's exact prompt (Section 3.2,
        QMR3). Requires ``paraphrase_llm_fn``. The rule-based fallback is OFF
        by default (``allow_rule_based_fallback``).
        """
        if self.paraphrase_llm_fn is None:
            logger.warning(
                "QMR3 skipped: no paraphrase_llm_fn provided (rule-based "
                "fallback is %s).",
                "enabled" if self.allow_rule_based_fallback else "disabled",
            )
            if not self.allow_rule_based_fallback:
                return None

        if self.paraphrase_llm_fn is not None:
            try:
                paraphrased = await self.paraphrase_llm_fn(
                    PARAPHRASE_PROMPT.format(question=question)
                )
                if paraphrased and paraphrased.strip():
                    return DrHallMutation(
                        mr_type=DrHallMR.QMR3.value,
                        follow_up_question=paraphrased.strip(),
                        original_question=question,
                        expected_relation="Answers should be semantically identical.",
                        metadata={"paraphrase_method": "llm",
                                  "kg_rule": _safe_get(row, "kg_rule"),
                                  "honest_mutation_type": _safe_get(row, "mutation_type")},
                    )
            except Exception as exc:  # noqa: BLE001 – log instead of silent pass
                logger.warning("QMR3 paraphrase_llm_fn failed: %s", exc)

        # Fallback: only when explicitly enabled; NOT the paper's method.
        if not self.allow_rule_based_fallback:
            return None
        paraphrased = self._rule_based_paraphrase(question)
        if paraphrased == question:
            return None
        return DrHallMutation(
            mr_type=DrHallMR.QMR3.value,
            follow_up_question=paraphrased,
            original_question=question,
            expected_relation="Answers should be semantically identical.",
            metadata={"paraphrase_method": "rule-based",
                      "kg_rule": _safe_get(row, "kg_rule"),
                      "honest_mutation_type": _safe_get(row, "mutation_type")},
        )

    # ----- QMR4: Adding External Knowledge -----
    def generate_qmr4(
        self, question: str, row: Optional[pd.Series] = None
    ) -> Optional[DrHallMutation]:
        """
        Inject external knowledge from the KG premise into the question.

        Paper Section 3.2, QMR4 retrieves evidence from Wikipedia. Here the
        evidence is taken from the dataset row (the KG premise), which is an
        explicitly-documented adaptation — see ``evidence_source`` in metadata.
        Pulling evidence from the same KG fact that generated the question can
        make the follow-up trivially consistent, so the source is recorded for
        downstream grouping.
        """
        if row is None:
            return None

        evidence, source_field = self._extract_evidence_from_row(row)
        if not evidence:
            return None

        follow_up = EXTERNAL_KNOWLEDGE_TEMPLATE.format(
            evidence=evidence,
            question=question,
        )
        return DrHallMutation(
            mr_type=DrHallMR.QMR4.value,
            follow_up_question=follow_up,
            original_question=question,
            expected_relation="Answers should be semantically identical (evidence is consistent).",
            metadata={
                "evidence": evidence,
                # Documented adaptation: paper uses Wikipedia; here it is the
                # KG premise present in the golden dataset.
                "evidence_source": source_field,
                "evidence_note": (
                    "Adapted from paper's Wikipedia retrieval to the KG premise "
                    "in the dataset; may weaken discriminative power."
                ),
                "kg_rule": _safe_get(row, "kg_rule"),
                "honest_mutation_type": _safe_get(row, "mutation_type"),
            },
        )

    # ----- CMR3: Composite Metamorphic Relation (paper §3.4, Table 2) -----
    async def generate_cmr3_async(
        self, question: str, row: Optional[pd.Series] = None
    ) -> List[DrHallMutation]:
        """
        CMR3 – DrHall's strongest detector (paper §3.4; F1 = 0.836 on
        FactHalluQA). Stacks the four Question MRs into ONE composed follow-up
        question (per language); the per-language answers are then **voted** –
        exactly like base QMR2 (see ``qmr2_vote``).

        Composition (faithful to the worked example in Table 2, where the CoT
        suffix appears verbatim and the evidence is shown in each language):

            1. QMR3 – paraphrase the *original question* (PARAPHRASE_PROMPT).
            2. QMR1 – append the CoT suffix **verbatim** to the paraphrase.
            3. QMR4 – wrap as "Known: [evidence] May I ask: [paraphrased+CoT]".
            4. QMR2 – translate the whole composed question into es/de/nl,
               producing three independent follow-up questions.

        Stacking-order note: §3.4 prose lists the MRs as "QMR1, QMR3, QMR2,
        QMR4", but the Table 2 worked example shows the CoT suffix appended
        *verbatim* (not paraphrased) and the evidence translated into each
        language. That requires QMR3 → QMR1 → QMR4 → QMR2. We follow Table 2,
        the authoritative artifact (the CMR1 example in Table 2 likewise shows
        a verbatim CoT appended after the paraphrase).

        Returns a list of mutations, one per language (mirrors
        ``generate_qmr2_async``), to be answered separately and voted
        downstream. Degrades gracefully (with warnings) when a required LLM
        callable is missing.
        """
        # Step 1 – QMR3 paraphrase (original question only).
        composed = question
        paraphrase_method = "none"
        if self.paraphrase_llm_fn is not None:
            try:
                paraphrased = await self.paraphrase_llm_fn(
                    PARAPHRASE_PROMPT.format(question=question)
                )
                if paraphrased and paraphrased.strip():
                    composed = paraphrased.strip()
                    paraphrase_method = "llm"
            except Exception as exc:  # noqa: BLE001
                logger.warning("CMR3 paraphrase step failed: %s", exc)
        else:
            logger.warning(
                "CMR3: no paraphrase_llm_fn; QMR3 step falls back to the "
                "original question (NOT paper-faithful)."
            )

        # Step 2 – QMR1 CoT suffix (verbatim).
        composed = composed.rstrip() + COT_SUFFIX

        # Step 3 – QMR4 external-knowledge wrap.
        evidence = ""
        evidence_source = ""
        if row is not None:
            evidence, evidence_source = self._extract_evidence_from_row(row)
        if evidence:
            composed = EXTERNAL_KNOWLEDGE_TEMPLATE.format(
                evidence=evidence, question=composed,
            )
        else:
            logger.warning(
                "CMR3: no evidence available in the row; QMR4 step is skipped "
                "(composed question used without the 'Known: [...]' wrapper)."
            )

        # Step 4 – QMR2 translate the composed question into each language.
        mutations: List[DrHallMutation] = []
        for lang in self.languages:
            translated, method = await self._translate_async(
                composed, lang, mr_label="CMR3",
            )
            degraded = method == "none"
            mutations.append(DrHallMutation(
                mr_type=DrHallMR.CMR3.value,
                follow_up_question=translated,
                original_question=question,
                expected_relation=(
                    "All CMR3 language variants should yield the same answer as "
                    "the original (QMR3+QMR1+QMR4+QMR2 stacked)."
                    + (" [DEGRADED: question not translated]" if degraded else "")
                ),
                metadata={
                    "language": lang,
                    "language_name": LANGUAGE_NAMES.get(lang, lang),
                    "translation_method": method,
                    "degraded": degraded,
                    "paraphrase_method": paraphrase_method,
                    "evidence_source": evidence_source,
                    "evidence": evidence,
                    "composed_english_question": composed,
                    "kg_rule": _safe_get(row, "kg_rule"),
                    "honest_mutation_type": _safe_get(row, "mutation_type"),
                },
            ))
        return mutations

    # ----- AMR1: General Question Construction -----
    def generate_amr1(
        self, question: str, answer: str, row: Optional[pd.Series] = None
    ) -> Optional[DrHallMutation]:
        """
        Negate the original answer to form a follow-up question (paper Section
        3.3, AMR1): ``[Original Answer] Is this statement not true?``

        The bracketed statement is the *original answer* (the LLM's declarative
        answer). If no ``statement_llm_fn`` is wired, the raw answer is used
        directly — closer to the paper than a mechanical concatenation. Use
        ``generate_amr1_async`` to declarativize the answer via an LLM.
        """
        if _is_missing(answer):
            return None

        statement = str(answer).strip()
        follow_up = AMR1_NEGATION_TEMPLATE.format(statement=statement)
        return DrHallMutation(
            mr_type=DrHallMR.AMR1.value,
            follow_up_question=follow_up,
            original_question=question,
            expected_relation="Follow-up should indicate the original answer is correct (NOT true = No).",
            metadata={"original_answer": answer,
                      "statement_source": "answer_direct",
                      "kg_rule": _safe_get(row, "kg_rule"),
                      "honest_mutation_type": _safe_get(row, "mutation_type")},
        )

    async def generate_amr1_async(
        self, question: str, answer: str, row: Optional[pd.Series] = None
    ) -> Optional[DrHallMutation]:
        """
        AMR1 with LLM declarativization of the answer (paper uses the LLM's own
        declarative answer). Falls back to the raw answer if no LLM or on error.
        """
        if _is_missing(answer):
            return None

        statement = str(answer).strip()
        statement_source = "answer_direct"
        if self.statement_llm_fn is not None:
            try:
                declarative = await self.statement_llm_fn(
                    AMR1_STATEMENT_PROMPT.format(question=question, answer=answer)
                )
                if declarative and declarative.strip():
                    statement = declarative.strip()
                    statement_source = "statement_llm_fn"
            except Exception as exc:  # noqa: BLE001
                logger.warning("AMR1 statement_llm_fn failed: %s", exc)

        follow_up = AMR1_NEGATION_TEMPLATE.format(statement=statement)
        return DrHallMutation(
            mr_type=DrHallMR.AMR1.value,
            follow_up_question=follow_up,
            original_question=question,
            expected_relation="Follow-up should indicate the original answer is correct (NOT true = No).",
            metadata={"original_answer": answer,
                      "statement": statement,
                      "statement_source": statement_source,
                      "kg_rule": _safe_get(row, "kg_rule"),
                      "honest_mutation_type": _safe_get(row, "mutation_type")},
        )

    async def generate_amr1_from_llm_answer_async(
        self, question: str, llm_answer: str, row: Optional[pd.Series] = None
    ) -> Optional[DrHallMutation]:
        """
        AMR1 built from the LLM's OWN answer ``a = P(q)`` — this is the
        paper-faithful path (paper §3.3 questions the *original answer*, i.e.
        the LLM's answer, not the golden label).

        The bracketed statement is *declarativized* per question type, because
        the KG-rule dataset's answers are short labels rather than the natural-
        language declarative sentences the paper's FactHalluQA yields:

        * **boolean** (yes_no / true_false): the proposition ``P`` is already
          embedded in the question ("... is it true that P?"). The LLM's
          True/False verdict is fused into ``P`` -> ``"It is true that P"`` /
          ``"It is NOT the case that P"``. This keeps AMR1 a meaningful negation
          probe instead of ``[True] Is this statement not true?``.
        * **multiple_choice**: the chosen letter is mapped to the *full option
          text* (via ``original_options``), which is the statement the LLM
          actually committed to -> ``"[option text] Is this statement not true?"``.
        * **wh / natural language**: the LLM's answer (a sentence) is used
          directly, optionally compressed via ``statement_llm_fn`` (paper's
          "Please try to answer in one sentence."). Mirrors ``generate_amr1_async``.

        Call this in the *answering* phase, where ``a = P(q)`` is available.
        """
        if _is_missing(llm_answer) or not str(llm_answer).strip():
            return None

        qtype = self._classify_question_type(question, row)
        statement = str(llm_answer).strip()
        statement_source = "answer_direct"

        if qtype == "boolean":
            prop = self._extract_boolean_proposition(question)
            verdict = self._parse_boolean_verdict(llm_answer)
            if prop and verdict is True:
                statement = f"It is true that {prop}"
                statement_source = "boolean_verdict"
            elif prop and verdict is False:
                statement = f"It is NOT the case that {prop}"
                statement_source = "boolean_verdict"
            elif prop:
                # Verdict unparsable: still better to embed the proposition than
                # to negate a bare "True"/"False". Fall back to the proposition.
                statement = prop
                statement_source = "boolean_proposition_fallback"
            # else: keep raw llm_answer.

        elif qtype == "multiple_choice":
            options = self._parse_mc_options(row, question)
            idx = self._parse_mc_option_index(llm_answer, len(options))
            if options and idx is not None and idx < len(options):
                statement = options[idx]
                statement_source = "mc_option_text"

        else:  # wh_question / natural language
            if self.statement_llm_fn is not None:
                try:
                    declarative = await self.statement_llm_fn(
                        AMR1_STATEMENT_PROMPT.format(
                            question=question, answer=llm_answer,
                        )
                    )
                    if declarative and declarative.strip():
                        statement = declarative.strip()
                        statement_source = "statement_llm_fn"
                except Exception as exc:  # noqa: BLE001
                    logger.warning("AMR1 statement_llm_fn failed: %s", exc)

        follow_up = AMR1_NEGATION_TEMPLATE.format(statement=statement)
        return DrHallMutation(
            mr_type=DrHallMR.AMR1.value,
            follow_up_question=follow_up,
            original_question=question,
            expected_relation=(
                "Follow-up should NOT contradict the LLM's original answer "
                "(negation probe; NOT true = No)."
            ),
            metadata={
                "original_answer": llm_answer,
                "statement": statement,
                "statement_source": statement_source,
                "question_type": qtype,
                "kg_rule": _safe_get(row, "kg_rule"),
                "honest_mutation_type": _safe_get(row, "mutation_type"),
            },
        )

    # ----- AMR2: Multi-Choice Question Construction -----
    async def generate_amr2_async(
        self,
        question: str,
        answer: str,
        row: Optional[pd.Series] = None,
    ) -> Optional[DrHallMutation]:
        """
        Generate a multiple-choice question following the paper's AMR2 design
        (Section 3.3, AMR2):
        1. Simplify the original answer into one word/phrase.
        2. Generate 2 distractors based on the simplified answer.
        3. Construct a multi-choice question with 3 named options + "none".
        """
        if _is_missing(answer):
            return None
        if self.distractor_llm_fn is None:
            logger.warning("AMR2 skipped: no distractor_llm_fn provided.")
            return None

        try:
            # Step 1: Simplify answer.
            simplified = str(answer)
            if self.simplify_llm_fn is not None:
                simplified_result = await self.simplify_llm_fn(
                    AMR2_SIMPLIFY_PROMPT.format(answer=answer)
                )
                if simplified_result and simplified_result.strip():
                    simplified = simplified_result.strip()

            # Step 2: Generate 2 distractors.
            distractors = await self.distractor_llm_fn(question, simplified)
            if not distractors or len(distractors) < 2:
                logger.warning("AMR2: distractor generation returned < 2 items; skipping.")
                return None
        except Exception as exc:  # noqa: BLE001
            logger.warning("AMR2 generation failed: %s", exc)
            return None

        import random
        rng = random.Random(42)
        # 2 distractors + 1 correct answer = 3 named options
        named_options = [answer] + list(distractors)[:2]
        rng.shuffle(named_options)

        # Step 3: Construct multi-choice in paper's format (Table 1, AMR2 Example).
        follow_up = AMR2_CHOICE_TEMPLATE.format(
            question=question,
            option_1=named_options[0],
            option_2=named_options[1],
            option_3=named_options[2],
        )
        return DrHallMutation(
            mr_type=DrHallMR.AMR2.value,
            follow_up_question=follow_up,
            original_question=question,
            expected_relation=(
                f"Follow-up should indicate '{answer}' is correct "
                f"among the named options."
            ),
            metadata={
                "original_answer": answer,
                "simplified_answer": simplified,
                "named_options": named_options,
                "kg_rule": _safe_get(row, "kg_rule"),
                "honest_mutation_type": _safe_get(row, "mutation_type"),
            },
        )

    # ----- Synchronous batch generators (LLM-free MRs only) -----

    def generate_qmr_mutations(
        self,
        row: pd.Series,
        question_col: str = "original_question",
    ) -> List[DrHallMutation]:
        """
        Synchronously generate QMR1, QMR2 and QMR4.

        NOTE: QMR3 (paraphrase) requires an LLM and is handled by
        ``generate_qmr3_async`` / ``generate_all_mutations_async``. QMR2 here is
        generated in *degraded* mode (no translation) unless a sync
        ``translate_fn`` is wired; use ``generate_qmr2_async`` for faithful
        translation.
        """
        question = str(row.get(question_col, "")).strip()
        if not question:
            return []

        mutations: List[DrHallMutation] = []
        mutations.append(self.generate_qmr1(question, row))
        mutations.extend(self.generate_qmr2(question, row))  # 3 per-language mutations
        qmr4 = self.generate_qmr4(question, row)
        if qmr4 is not None:
            mutations.append(qmr4)
        return mutations

    def generate_amr_mutations(
        self,
        row: pd.Series,
        question_col: str = "original_question",
        answer_col: str = "original_correct_answer",
    ) -> List[DrHallMutation]:
        """
        Synchronously generate AMR1 only (no LLM). AMR2 requires an LLM and is
        handled by ``generate_amr2_async`` / ``generate_all_mutations_async``.
        """
        question = str(row.get(question_col, "")).strip()
        answer = row.get(answer_col, "")
        if not question or _is_missing(answer):
            return []

        amr1 = self.generate_amr1(question, str(answer), row)
        return [amr1] if amr1 is not None else []

    async def generate_all_mutations_async(
        self,
        row: pd.Series,
        question_col: str = "original_question",
        answer_col: str = "original_correct_answer",
    ) -> List[DrHallMutation]:
        """
        Generate **all six** MRs in one call (paper-faithful).

        QMR3/AMR2/QMR2-translation use their LLM callables when available. MRs
        whose required LLM callable is missing are **skipped with a warning**
        (never silently dropped), so the caller can tell exactly which MRs were
        produced.
        """
        question = str(row.get(question_col, "")).strip()
        answer = row.get(answer_col, "")

        mutations: List[DrHallMutation] = []

        # --- LLM-free MRs ---
        mutations.append(self.generate_qmr1(question, row))
        mutations.append(self.generate_qmr4(question, row))

        # --- QMR2 (translation) ---
        mutations.extend(await self.generate_qmr2_async(question, row))

        # --- QMR3 (paraphrase) ---
        qmr3 = await self.generate_qmr3_async(question, row)
        if qmr3 is not None:
            mutations.append(qmr3)

        # --- AMR1 ---
        if not _is_missing(answer):
            amr1 = await self.generate_amr1_async(question, str(answer), row)
            if amr1 is not None:
                mutations.append(amr1)

        # --- AMR2 ---
        if not _is_missing(answer):
            amr2 = await self.generate_amr2_async(question, str(answer), row)
            if amr2 is not None:
                mutations.append(amr2)

        return mutations

    # ----- Serialization helpers -----
    @staticmethod
    def mutation_to_dict(m: DrHallMutation) -> Dict[str, Any]:
        return {
            "mr_type": m.mr_type,
            "follow_up_question": m.follow_up_question,
            "original_question": m.original_question,
            "expected_relation": m.expected_relation,
            "metadata": m.metadata,
        }

    @staticmethod
    def mutations_to_json(mutations: List[DrHallMutation]) -> str:
        return json.dumps(
            [DrHall.mutation_to_dict(m) for m in mutations],
            ensure_ascii=False,
        )

    # ----- Answer-consistency assessment helpers (paper Section 3.5) -----

    @staticmethod
    def build_simplify_prompt(answer: str) -> str:
        """Build the paper's answer-simplification prompt."""
        return ANSWER_SIMPLIFY_PROMPT.format(answer=answer)

    @staticmethod
    def build_consistency_judge_prompt(
        original_answer: str, follow_up_answer: str
    ) -> str:
        """
        Build a consistency-judge prompt combining the two (processed) answers
        and the paper's exact judge instruction.
        """
        return (
            f"Answer A: {original_answer}\n"
            f"Answer B: {follow_up_answer}\n\n"
            f"{CONSISTENCY_JUDGE_PROMPT}"
        )

    @staticmethod
    def parse_consistency(verdict_text: str) -> Optional[bool]:
        """
        Parse the consistency-judge verdict.

        Returns ``True`` if consistent, ``False`` if inconsistent, ``None`` if
        unparseable. The paper maps Yes->consistent, No->inconsistent.
        """
        if not verdict_text or not str(verdict_text).strip():
            return None
        text = str(verdict_text).strip().lower()
        # Prefer an exact-ish leading token.
        first = text.split()[0] if text.split() else ""
        if first in {"yes", "consistent", "right", "correct"}:
            return True
        if first in {"no", "inconsistent", "wrong", "not"}:
            return False
        if "not" in text and "consistent" in text:
            return False
        if "consistent" in text or "yes" in text:
            return True
        if "no" in text or "wrong" in text:
            return False
        return None

    # ----- Internal helpers -----

    # ----- AMR1 answer-declarativization helpers (boolean / MC / WH) -----
    # The paper's AMR1 negates the LLM's *declarative* answer. Our KG-rule
    # dataset answers are short labels, so we must reconstruct a statement per
    # question type. These helpers are deterministic (no LLM).

    @staticmethod
    def _classify_question_type(
        question: str, row: Optional[pd.Series]
    ) -> str:
        """Classify a row into 'boolean' | 'multiple_choice' | 'wh_question'.

        Prefers the dataset's explicit ``original_question_type`` tag; falls
        back to regex on the question text.
        """
        qt = _safe_get(row, "original_question_type").strip().lower()
        if qt in ("true_false", "yes_no"):
            return "boolean"
        if qt == "multiple_choice":
            return "multiple_choice"
        if qt == "wh_question":
            return "wh_question"
        # Infer from question text.
        q = (question or "").strip().lower()
        if re.search(r"\bis it (?:true|the case) that\b", q):
            return "boolean"
        if "which of the following" in q:
            return "multiple_choice"
        return "wh_question"

    @staticmethod
    def _extract_boolean_proposition(question: str) -> Optional[str]:
        """Extract proposition P from "... is it true that P?".

        Returns None if the boolean-question pattern is not found.
        """
        m = re.search(
            r"\bis it (?:true|the case) that\s+(.+?)\?\s*$",
            question or "",
            re.IGNORECASE | re.DOTALL,
        )
        if not m:
            return None
        return m.group(1).strip().strip(".").strip()

    @staticmethod
    def _parse_boolean_verdict(answer: Any) -> Optional[bool]:
        """Parse the LLM's boolean answer into True/False/None."""
        if _is_missing(answer):
            return None
        t = str(answer).strip().lower()
        if not t:
            return None
        first = re.split(r"[\s,.;:!?]+", t, maxsplit=1)[0]
        if first in ("true", "yes", "correct", "affirmative", "right"):
            return True
        if first in ("false", "no", "incorrect", "wrong", "negative"):
            return False
        if re.search(r"\bnot (?:true|the case)\b", t) or "is false" in t:
            return False
        if "is true" in t or "it is true" in t:
            return True
        if "false" in t:
            return False
        if "true" in t:
            return True
        return None

    @staticmethod
    def _parse_mc_options(
        row: Optional[pd.Series], question: str = ""
    ) -> List[str]:
        """Parse MC option texts in A/B/C/D order.

        Prefers the dataset's ``original_options`` JSON list (index 0 == A);
        falls back to parsing 'A. ... B. ...' from the question.
        """
        if row is not None:
            raw = row.get("original_options", "")
            if not _is_missing(raw):
                s = str(raw).strip()
                if s and s != "[]":
                    try:
                        opts = json.loads(s)
                        if isinstance(opts, list) and opts:
                            return [str(o).strip() for o in opts if str(o).strip()]
                    except (json.JSONDecodeError, TypeError):
                        pass
        # Fallback: parse from the question body.
        if question:
            matches = re.findall(
                r"\b([A-D])\.\s*(.+?)(?=\n\s*[A-D]\.|\s*$)",
                question,
                re.DOTALL,
            )
            opts = [text.strip() for _, text in matches if text.strip()]
            if opts:
                return opts
        return []

    @staticmethod
    def _parse_mc_option_index(answer: Any, n_options: int) -> Optional[int]:
        """Map an LLM MC answer to a 0-based option index, or None.

        Handles 'A', 'a', '(A)', 'A.', 'Option A', etc.
        """
        if _is_missing(answer) or n_options <= 0:
            return None
        t = str(answer).strip()
        m = re.match(r"^\(?([A-Da-d])\)?[.\):\s]", t)
        if not m:
            m = re.match(r"^([A-Da-d])$", t)
        if m:
            idx = ord(m.group(1).upper()) - ord("A")
            if 0 <= idx < n_options:
                return idx
        return None

    @staticmethod
    def _extract_evidence_from_row(row: pd.Series) -> "tuple[str, str]":
        """Extract evidence string + the source field name from a golden row."""
        # Try natural_language first (readable description of the rule).
        for field_name in ("natural_language", "original_instance", "entity_labels"):
            val = row.get(field_name, "")
            if not _is_missing(val) and str(val).strip():
                return str(val).strip(), field_name
        return "", ""

    @staticmethod
    def _rule_based_paraphrase(question: str) -> str:
        """
        Simple rule-based paraphrase for questions following the
        "Given that X, ..." pattern. NOT the paper's method — only used when
        ``allow_rule_based_fallback=True``.
        """
        q = question.strip()

        m = re.match(r"^Given that (.+?),\s*(is it true that .+)$", q, re.IGNORECASE)
        if m:
            premise, query = m.groups()
            return f"{query.rstrip('?')}, given that {premise}?"

        m = re.match(r"^Given that (.+?),\s*(what .+)$", q, re.IGNORECASE)
        if m:
            premise, query = m.groups()
            return f"Based on the fact that {premise}, {query}"

        m = re.match(r"^Based on the premise that (.+?),\s*(.+)$", q, re.IGNORECASE)
        if m:
            premise, query = m.groups()
            return f"Given that {premise}, {query}"

        m = re.match(r"^Given that (.+?),\s*(which .+)$", q, re.IGNORECASE)
        if m:
            premise, query = m.groups()
            return f"Considering that {premise}, {query}"

        return f"Please answer the following: {q}"


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _safe_get(row: Optional[pd.Series], key: str, default: str = "") -> str:
    if row is None:
        return default
    val = row.get(key, default)
    if _is_missing(val):
        return default
    return str(val)


def _is_missing(value: Any) -> bool:
    """Robust missing-value check (handles None, NaN, list/array edge cases)."""
    if value is None:
        return True
    if isinstance(value, (dict, list, tuple)):
        return False
    try:
        return bool(pd.isna(value))
    except (TypeError, ValueError):
        return False


def _is_async_callable(fn: Optional[Callable]) -> bool:
    """True if ``fn`` is an async callable (coroutine function)."""
    if fn is None:
        return False
    return inspect.iscoroutinefunction(fn)
